apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-system

commonLabels:
  app.kubernetes.io/name: elasticsearch-reindexer

resources:
- job.yaml

configMapGenerator:
  - name: reindex-script
    files:
      - reindex.sh
secretGenerator:
  - name: reindexer-env
    env: reindexer.env
